COURSE_DETAILS = {
    "1B01PHY": "Mechanics 1",
    "2B02PHY": "Mathematical Physics and Error Analysis",
    "3B03PHY": "Mechanics II",
    "4B04PHY": "Electronics I",
    "4B05PHY": "General Physics Practical I",
    "5B06PHY": "Quantum Mechanics",
    "5B07PHY": "Electrostatics and Magnetostatics",
    "5B08PHY": "Thermodynamics and Statistical Mechanics",
    "5B09PHY": "Electronics II",
    "5B10PHY": "Atomic, Nuclear and  Particle Physics",
    "6B11PHY": "Optics and Photonics",
    "6B12PHY": "Nuclear, Particle and Astrophysics",
    "6B13PHY": "Electrodynamics and Circuit Theory",
    "6B14PHY": "Material Science",
    "6B15PHY(A)": "Plasma Physics",
    "6B15PHY(B)": "Astronomy & Astrophysics",
    "6B15PHY(C)": "Atmospheric Physics",
    "6B15PHY(D)": "Nanoscience",
    "6B15PHY(E)": "Material Science",
    "6B15PHY(F)": "Computational Physics",
    "6B16PHY": "Electronics Practical III",
    "6B16/17PHY": "Practical 2 & 3",
    "6B17PHY": "Project",
    "6B18PHY": "Project",
    "1C01PHY": "Mechanics",
    "2C02PHY": "Electricity, Magnetism and Thermodynamics",
    "3C03PHY": "Optics and Photonics",
    "4C04PHY": "Electronics and Modern Physics",
    "4C05PHY": "Physics Practical",
    "5D01PHY(A)": "Environmental Physics",
    "5D01PHY(B)": "Joy of Star Watching",
    "5D01PHY(C)": "Disaster Management",
    "5D01PHY(D)": "Biophysics",
    "1C01CSC": "Introduction to Computer and Programming",
    "2C02CSC": "Programming in C",
    "3C03CSC": "Web Technology with Database Management System",
    "4C04CSC": "Computation Using Python",
    "4C05CSC": "Lab 1: Programming In C, Web Programming and Python Programming",
    "1A07HIN": "Hindi Kavitha",
    "2A08HIN": "Rachana Thatha Prayog",
    "3A09HIN": "Katha Sahithya",
    "4A10HIN": "Natak Aur Ekangi",
    "1A07-1HIN": "Kavitha Aur Kahani",
    "2A08-1HIN": "Vyavaharik HIndi",
    "1A07-2HIN": "Naya Sahithya",
    "2A08-2HIN": "Sahithya Aur Prayog",
    "1B01MAT": "Set Theory, Differential Calculus and Numerical Methods",
    "2B02MAT": "Integral Calculus and Logic",
    "3B03MAT": "Analytic Geometry and Applications of Derivatives",
    "4B04MAT": "Number Theory and Applications of Integrals",
    "5B05MAT": "Set Theory, Theory of Equations and Complex Numbers",
    "5B06MAT": "Real Analysis I",
    "5B07MAT": "Abstract Algebra ",
    "5B08MAT": "Differential Equations and Laplace Transforms",
    "5B09MAT": "Vector Calculus",
    "6B10MAT": "Real Analysis II",
    "6B11MAT": "Complex Analysis",
    "6B12MAT": "Numerical Methods, Fourier Series and Partial Differential Equations",
    "6B13MAT": "Linear Algebra",
    "6B14AMAT": "Operations Research",
    "6B14BMAT": "Mathematical Economics",
    "6B14CMAT": "Classical Mechanics",
    "6B14DMAT": "Programming in Python",
    "6B15MAT": "Project",
    "5D01MAT": "Quantitative Arithmetic and Reasoning",
    "5D02MAT": "Astronomy",
    "5D03MAT": "Quantitative Arithmetic and Reasoning",
    "5D04MAT": "Graph Theory",
    "1C01MAT-PH": "Mathematics for Physics I",
    "2C02MAT-PH": "Mathematics for Physics II",
    "3C03MAT-PH": "Mathematics for Physics III",
    "4C04MAT-PH": "Mathematics for Physics IV",
    "1C01MAT-CH": "Mathematics for Chemistry I",
    "2C02MAT-CH": "Mathematics for Chemistry II",
    "3C03MAT-CH": "Mathematics for Chemistry III",
    "4C04MAT-CH": "Mathematics for Chemistry IV",
    "1C01MAT-ST": "Mathematics for Statistics I",
    "2C02MAT-ST": "Mathematics for Statistics II",
    "3C03MAT-ST": "Mathematics for Statistics III",
    "4C04MAT-ST": "Mathematics for Statistics IV",
    "1B01STA": "Introductory Statistics",
    "2B02STA": "Probability Theory and Mathematical Expectation",
    "3B03STA": "Probability Distribution and Limit Theorems",
    "4B04STA": "Statistical Inference – I",
    "5B05STA": "Statistical Inference - II",
    "5B06STA": "Mathematical Methods for Statistics - I",
    "5B07STA": "Regression Techniques and Time Series",
    "5B08STA": "Statistical Quality Control and Operations Research",
    "5B09STA": "Practical Using R - I ",
    "6B10STA": "Mathematical Methods for Statistics – II ",
    "6B11STA": "Mathematical Methods for Statistics – III",
    "6B12STA": "Sampling Techniques and Design of Experiments",
    "6B13STA": "Actuarial Statistics",
    "6B14STA": "Practical Using R – II",
    "6B15STA": "Project",
    "5D01STA": "Basics of Statistics",
    "5D02STA": "Sampling Techniques",
    "5D03STA": "Computer Oriented Data Analysis",
    "1C01STA": "Basics Statistics",
    "2C02STA": "Probability Theory and Random Variables",
    "3C03STA": "Probability Distributions",
    "4C04STA": "Statistical Inference",
    "5B07ECO": "Basic Tools for Economic Analysis-I",
    "6B12ECO": "Basic Tools for Economic Analysis II",
    "1B01PCH": "Theoretical and Inorganic Chemistry",
    "2B02PCH": "Analytical and Inorganic Chemistry I",
    "3B04CHE": "Organic Chemistry I",
    "4B06CHE": "Organic Chemistry II",
    "3B03CHE": "Core Course Practicals 1 Volumetric Analysis",
    "4B03CHE": "Core Course Practicals 1 Volumetric Analysis",
    "3B05CHE": "Core Course Practicals 2 Core Course Practicals 2 Inorganic Qualitative Analysis",
    "4B05CHE": "Core Course Practicals 2 Core Course Practicals 2 Inorganic Qualitative Analysis",
    "5B07CHE": "Inorganic Chemistry I",
    "5B08CHE": "Inorganic Chemistry II",
    "5B09CHE": "Physical Chemistry I",
    "5B10CHE": "Physical Chemistry II",
    "6B14CHE": "Organic Chemistry III",
    "6B15CHE": "Physical Chemistry III",
    "6B16CHE": "Physical Methods in Chemistry",
    "6B17CHE-A": "Environmental Chemistry",
    "6B17CHE-B": "Applied Chemistry",
    "6B17CHE-C": "Polymer Chemistry",
    "6B17CHE-D": "Nano Chemistry",
    "5B11CHE": "Core Course Practicals 3 Gravimetric Analysis",
    "6B11CHE": "Core Course Practicals 3 Gravimetric Analysis",
    "5B12CHE": "Core Course Practicals 4 Organic Chemistry",
    "6B12CHE": "Core Course Practicals 4 Organic Chemistry",
    "6B18CHE": "Core Course Practicals 5 Physical Chemistry",
    "5B13CHE": "Industrial Visit",
    "6B13CHE": "Project",
    "5D01CHE": "Chemistry In Service To Man",
    "5D02CHE": "Drugs-Use & Abuse",
    "5D03CHE": "Environmental Studies",
    "5D04CHE": "Nanomaterials",
    "1C01CHE": "Chemistry (For Physical & Biological Sciences)",
    "2C02CHE": "Chemistry (For Physical & Biological Sciences)",
    "3C03CHE(BS": "Chemistry (For Biological Science)",
    "3C03CHE(PS": "Chemistry (For Physical Science)",
    "4C04CHE(BS": "Chemistry (For Biological Science)",
    "4C04CHE(PS": "Chemistry (For Physical Science)",
    "4C05CHE": "Complementary Elective Course Practical ",
    "1B01ZLG": "Protista and Non Chordata-I",
    "4B01ZLG-P": "Practical-I",
    "2B02ZLG": "Non Chordata-II",
    "3B03ZLG": "Chordata - I",
    "4B04ZLG": "Chordata-II and Comparative Anatomy",
    "5B05ZLG": "Evolution, Ethology and Research Methodology",
    "5B06ZLG": "Animal Physiology",
    "5B07ZLG": "Biochemistry and Biophysics",
    "5B08ZLG": "Genetics",
    "5B09ZLG": "Comparative Animal Physiology & Human Physiology.",
    "6B02ZLG-P": "Core Practical II",
    "6B10ZLG": "Molecular Biology and Bioinformatics",
    "6B11ZLG": "Environmental Science",
    "6B12ZLG": "Developmental Biology",
    "6B13ZLG": "Project",
    "6B14ZLG": "Applied Zoology",
    "6B03ZLG-P": "Core Practical III",
    "6B15ZLG": "Project",
    "5D01ZLG": "Nutrition and Health",
    "5D02ZLG": "Apiculture",
    "5D04ZLG": "Reproductive Health and Sex Education",
    "1C01ZLG": "Diversity of Life - I Protistans and Non Chordates",
    "4C05ZLG-P": "Practical",
    "2C02ZLG": "Diversity of Life-II Chordata Form and Functions",
    "3C03ZLG": "Animal Physiology",
    "4C04ZLG": "Medical Zoology",
    "1B01BOT/PL": "Environmental Science and Phytogeography",
    "2B02BOT/PL": "Reproductive Botany",
    "3B03BOT/PL": "Phycology, Mycology and Lichenology",
    "3A11PLS": "Plantation Science",
    "3A12PLS": "Horticulture",
    "4B04BOT/PL": "Bryology, Pteridology, Gymnosperms and Paleobotany",
    "4A13PLS": "Plantation Management",
    "4A14PLS": "Herbal Science",
    "4B05BOT/PL": "Core Practical I",
    "4A15PLS": "General Practical",
    "5B06BOT/PL": "Taxonomy, Morphology and Economic Botany",
    "5B07BOT/PL": "Microbiology and Plant Pathology",
    "5B08BOT/PL": "Plant Physiology and Biochemistry",
    "5B09BOT/PL": "Bioinformatics, Instrumentation and Research Methodology",
    "6B10BOT/PL": "Plant Tissue culture, Embryology and Palynology",
    "6B11BOT/PL": "Genetics, Biostatitics and Evolution",
    "6B12BOT/PL": "Biotechnology and Crop improvement",
    "6B13BOT/PL": "Cell and Molecular Biology",
    "6B14BOT/PL": "Core Practical II",
    "6B15BOT/PL": "Core Practical III",
    "6B16BOT/PL": "Project",
    "1C01BOT/PL": "Diversity of Life-Microbes & Thallophytes",
    "2C02BOT/PL": "Archaegoniatae, Palaeobotany And Reproduction In Angiosperms",
    "3C03BOT/PL": "Angiosperms–Morphology, Systematics, Utility, Plant Breeding and Plant Pathology",
    "4C04BOT/PL": "Angiosperm - Anatomy and Physiology",
    "4C05BOT/PL": "Practical Paper - I",
    "5D01BOT/PL": "Mushroom Cultivation and Marketing",
    "5D02BOT/PL": "Medicinal Plants",
    "5D03BOT/PL": "Environmental Science",
    "1B01ECO": "Micro Economic Analysis-I",
    "2B02ECO": "Micro Economic Analysis-II",
    "3B03ECO": "Central Themes in Indian Economy",
    "3B04ECO": "International Economics",
    "4B05ECO": "Research Methods and Techniques for Economic Analysis",
    "4B06ECO": "Environmental Economics",
    "5B08ECO": "Alternative Economics",
    "5B09ECO": "Research Methods and Techniques for Economic Analysis",
    "5B10ECO": "Development Economics",
    "5B11ECO": "Economics of Banking and Finance",
    "6B13ECO": "Macro Economics Analysis II",
    "6B14ECO": "Puublic Economics",
    "6B15ECO": "Basic Econometric Analysis",
    "6B16ECO": "Project",
    "5D01ECO": "Basics of Economics",
    "5D02ECO": "Kerala Economy",
    "5D03ECO": "Economics of Share Market",
    "1C09ECO": "Population and Development",
    "2C10ECO": "Economic Geography",
    "1C05ECO": "Introductory Economics-I",
    "2C06ECO": "Introductory Economics II",
    "1A07MAL": "Kadha Mathrukakal",
    "2A08MAL": "Kavitha Mathrukakal",
    "3A09MAL": "Gadya Sahithyam",
    "4A10MAL": "Drishya Kala Sahithyam",
    "1A07-1MAL": "Sahithyaroopangal",
    "2A08-1MAL": "Gadyaroopangal",
    "1A07-2MAL": "Sahitya Ganangal",
    "2A08-2MAL": "Gadya Mathrukakal",
    "5D01MAL": "Chalachithra Padanangal",
    "5D02MAL": "Malayalam Computing",
    "5D03MAL": "Keraleeyakalakal",
    "1B01MAL": "Malayala Kavitha - Adhunikam Adhunikaantharam",
    "2B02MAL": "Cherukatha Sahithyam",
    "3B03MAL": "Malayalasahithya Vimarshanam",
    "3B04MAL": "Indian Kavyasidhaanthangal",
    "4B05MAL": "Paaschaathya Saahithya Sidhaanthangal",
    "4B06MAL": "Praacheena Madhyakaala Saahithyam",
    "5A07MAL": "Bhaasha Shaasthravaum Vyakaranavum",
    "5A08MAL": "Novel Sahithyam",
    "5B09MAL": "Samskara Padanavum Sahithyavum",
    "5B10MAL": "Kerala Samskaram",
    "5B11MAL": "Nadodi Vijnaaneeyam",
    "6B12MAL": "Bhasha Shasthram",
    "6B13MAL": "Maadhyama Padanam",
    "6B14MAL": "Vivara Sankethika Vidyayum Malayalavum",
    "6B15MAL": "Vivarthana Sahithyam",
    "6B16MAL": "Project",
    "1C01MAL": "Paristhithi Dalit Linga Padavi Padanangal",
    "4C04MAL": "Malabar Padanangal",
    "3A11PCH": "Polymer Chemistry I",
    "3A12PCH": "Polymer Chemistry II",
    "3A12(A)PCH": "Polymer Chemistry II (Practical)",
    "4A13PCH": "Polymer Chemistry III",
    "4A13(A)PCH": "Polymer Chemistry III (Practical)",
    "4A14PCH": "Polymer Chemistry IV",
    "1A01ENG": "Communicative English",
    "1A02ENG": "Readings on Kerala",
    "2A03ENG": "Readings on Life and Nature",
    "2A04ENG": "Readings on Gender",
    "3A05ENG": "Readings on Democracy and Secularism",
    "4A06ENG": "Readings on Philosophy of Knowledge",
    "1B01COM": "Management Concepts & Principles",
    "1B02COM": "Financial Accounting",
    "1C01COM": "Business Statistics",
    "2B03COM": "Principles of Marketing",
    "2B04COM": "Human Resource Management",
    "2C02COM": "Quantitative Techniques for Business Decision",
    "3A11COM": "Disaster Management",
    "3A12COM": "Entrepreneurship Development",
    "3C03COM": "Business Economics",
    "3B05COM": "Advanced Accounting",
    "3B06COM": "Co-Operative Principles",
    "3C04COM": "Business Regulatory Framework",
    "4A13COM": "General Informatics Skills",
    "4A14COM": "Environmental Studies and Disaster Management",
    "4B07COM": "Income Tax Law & Practice I",
    "4B08COM": "Informatics Skills",
    "4B09COM": "Management of Co-operatives",
    "4C05COM": "Corporate Law & Business Regulation",
    "5B10COM": "Banking Principles and Operations",
    "5B11COM": "Co-operative Laws",
    "5B12COM": "Auditing",
    "5B13COM": "Income Tax Law & Practice II",
    "5B14COM": "Co-Operative Laws",
    "5D01COM": "Basic Accounting",
    "6B15COM": "Income Tax and GST",
    "6B16COM": "Co-operative Accounting and Legislations",
    "6B17COM": "Project",
    "6B18COM": "Financial Markets & Services",
    "6B19COM": "Co-operative Accounting and Legislations",
    "6B20COM": "Project",
    "1B01HIS": "History of India I: Pre-historic Times to c.200 CE ",
    "2B02HIS": "Cultural Transformations in Europe",
    "3B03HIS": "History of India II: Polity, Society and Culture (c.200 to 1206)",
    "3B04HIS": "History of Kerala I: Earliest Times to c.1500 CE",
    "4B05HIS": "History of India III: Sultanate to British Conquest (1206 -1757)",
    "4B06HIS": "Ideologies and Revolutions in the Modern World ",
    "5B07HIS": "Social Formation in Medieval India",
    "5B08HIS": "Social Movements and Political Awakening in Modern Kerala",
    "5B09HIS": "Historiography",
    "5B10HIS": "Method and Writing of History",
    "5B11HIS": "Archival Studies and Social Informatics",
    "6B12HIS": "Indian Historiography",
    "6B13HIS": "Problems in Contemporary World",
    "6B14HIS": "Colonialism and Transformation of Indian Society",
    "6B15HIS": "Freedom Struggle in India",
    "6B16HIS": "Project",
    "5D01HIS": "Social Reform Movements in Kerala",
    "5D02HIS": "India's Struggle for Freedom",
    "5D03HIS": "Cultural Heritage of North Malabar",
    "3C07HIS": "Economic Historyof Modern India 1793 - 1947",
    "4C08HIS": "lndian National Movement",
    "3C(02)SKT-": "Nataka and Vykarana",
    "2C(01)SKT": "Kavya and Vyakarana",
    "4C04POL": "Dynamics of Indian Political System",
    "5D02CSC": "Web Technology",
    "5D01SKT": "Vyavaharik Samskrita",
    "3C03POL": "Foundations of Political Science",
    "5D01POL": "Human Rights in India",
    "1B01PLS": "Cytology and Angiosperm Anatomy",
    "4B05PLS": "Core Practical I",
    "1C01BOT": "Microbiology, Phycology, Mycology and Lichenology",
    "4C05PLS": "CE Practical - Botany",
    "1A11COM": "Business Statistics and Basic Numerical\r\nSkills",
    "2C01SKT-ML": "Kavya and Vyakarana",
    "2B02COM": "Functional Applications of Management",
    "2C01COM": "Quantitative Techniques for Business Decision",
    "2C02BOT": "Bryology, Pteridology, Gymnosperm Biology, Palaeobotany, Phytopathology and Angiosperm Embryology",
    "5B07ECO ": "Basic Tools for Economic Analysis I",
    "5B08ECO ": "Heterodox Economics",
    "5B09ECO ": "Macroeconomic Analysis I",
    "5B10ECO ": "Developemnt Economics",
    "5B11ECO ": "Economics of Banking and Finance",
    "5B07PCH": "Analytical and Inorganic Chemistry - II",
    "5B08PCH": "Inorganic Chemistry",
    "5B09PCH": "Physical Chemistry - I",
    "5B10PCH": "Physical Chemistry - II",
    "5B11PCH": "Practicals 3: Gravimetric Analysis ",
    "5B12PCH": "Practicals 4: Organic Chemistry",
    "5B13PCH": "Project & Industrial Visit",
    "6B15PHY": "General Physics Practical II",
    "5B07HIS ": "History of India IV: Colonial Transformations (1757-1885)",
    "5B08HIS ": "History of India V: Making of the Nation (1885 -1947)",
    "5B09HIS ": "History of Kerala II: Making of Modern Kerala (1500-1970)",
    "5B10HIS ": "Method and Writing of History",
    "5B11HIS ": "Historiography: Perspectives and Practices",
    "3B04ICSC": "Python for Machine Learning",
    "3B05ICSC": "Operating System",
    "3B06ICSC": "Data Structures",
    "3B07ICSC": "Lab-2 : Python for Machine Learning",
    "3B08ICSC": "Lab-3 : Data Structures using C",
    "4B09ICSC": "Computer Organization",
    "4B10ICSC": "Database Management System",
    "4B11ICSC": "Object Oriented Programming using Java",
    "4B12ICSC": "Lab-4 : Object Oriented Programming using Java",
    "4B13ICSC": "Lab-5: Database Management System",
    "5B07COM": "Business Research Methodology",
    "5B08COM": "Income Tax Law and Practice",
    "5B09COM": "Cost Accounting",
    "5B06PLS": "Angiosperm Systematics and Ethnobotany",
    "5B07PLS": "Plant Physiology and Metabolism",
    "5B08PLS": "Microbiology, Mycology, Lichenology and Phytopathology",
    "5B09PLS": "Research Methodology, Instrumentation and Biostatistics",
    "6B14PLS": "Core Practical II",
    "6B15PLS": "Core Practical III",
    "5D01BOT": "Mushroom Cultivation",
    "3B03PLS": "Plant Diversity I – Algae and Bryophytes",
    "3C03BOT": "Angiosperm Morphology, Anatomy and Systematics",
    "5B07MAL": "Vyakarana Padanangal",
    "5B08MAL": "Novel Sahithyam",
    "5D04MAL": "Vaikkom Muhammed Basheer - Paadavum Padanavum",
    "3C02SKT-ML": "Nataka and Vyakarana",
    "3B04PCH": "Organic Chemistry - I",
    "3B03PCH": "Core Course Practicals 1 - Volumetric Analysis",
    "3B05PCH": "Polymer Chemistry II (Practical)",
    "3C03CHE-BS": "Chemistry (For Biological Science)",
    "3C03CHE-PS": "Chemistry (For Physical Science) ",
    "3C03MAT-ICS": "Foundation Mathematics for Machine Learning I",
    "3C03STA-ICS": "Probability Distributions",
    "3B03COM": "Advanced Accounting",
    "3B04COM": "Co-operative Principles",
    "3C02COM": "Business Regulatory Framework",
    "ENG3C08": "Twentieth Century British Literature",
    "ENG3C09": "Linguistics",
    "ENG3C10": "Indian Writing in English",
    "ENG3C11": "American Literature",
    "ENG3E08": "European Fiction",
    "4C04MAT-ICS": "Foundation Mathematics for Machine Learning II",
    "4C04STA-ICS": "Statistical Inference",
    "5D03BOT": "Plant Propagation",
    "5D03COM": "Principles of Management",
    "5D05CSC": "Python Programming",
    "5D03PHY": "Biophysics",
    "5D05PHY": "Electricity in Daily Life",
    "5D02SKT": "Herbal Literacy and Ethnobotanical Awareness",
    "5D052SKT": "Literary Wolrd of Kalidasa",
    "5D04STA": "Index Numbers and Time Series",
    "5D03ZLG": "Sericulture",
    "5D05PED": "Exercise is Medicine",
    "1B01ICSC": "Introduction to C Programming",
    "2B03ICSC": "Lab 1 - C Programming",
    "1C01MAT-ICS": "Differential Calculus and Linear Algebra I",
    "1C01STA-ICS": "Basic Statistics",
    "6B14MAT": "Operations Research",
    "6B12HIS ": "History of India VI: Developments since Independence (1947 - 2000)",
    "6B13HIS ": "History of the Contemporary World (1945-2000)",
    "6B14HIS ": "Indian Historiography",
    "6B15HIS ": "Project",
    "4B04PLS": "Plant Diversity II – Pteridophytes and Gymnosperms",
    "6B10PLS": "Environmental Science and Phytogeography",
    "6B11PLS": "Genetics, Molecular Biology and Plant Breeding",
    "6B12PLS": "Biotechnology and Bioinformatics ",
    "6B13PLS": "Evolution and Palaeobotany",
    "4B06PCH": "Organic Chemistry-II",
    "4B05PCH": "Core Course Practicals 2 - Inorganic Qualitative Analysis",
    "4B03PCH": "Core Course Practicals 1 - Volumetric Analysis",
    "5B14ICSC": "Introduction to Artificial Intelligence",
    "5B15ICSC": "Software Engineering",
    "5B16ICSC": "UNIX Shell Programming",
    "5B17ICSC": " Introduction to Machine Learning",
    "5B18ICSC": "Lab-6 : UNIX Shell Programming",
    "5B19ICSC": "Lab-7: Machine Learning",
    "6B10PHY": "Solid State Physics and Spectroscopy",
    "2C02MAT-ICS": "Differential Calculus and Linear Algebra II",
    "2C02STA-ICS": "Probability Theory and Random Variables",
    "6B13ASTA": "Applied Statistics",
    "6B09ZLG": "Cell Biology, Immunology and Microbiology",
    "4B05COM": "Corporate Accounting",
    "4B06COM": "Management of Cooperatives",
    "4C04COM": "Corporate Law and Business Regulations",
    "6B12COM": "Financial Markets and Services",
    "6B13COM": "Management Accounting",
    "6B14COM": "Auditing and Corporate Governance",
    "6B16HIS-B": "Environmental History of India",
    "4C04CHE-BS": "Chemistry (For Biological Science)",
    "4C04CHE-PS": "Chemistry (For Physical Science) ",
    "6B14PCH": "Organic Chemistry III",
    "6B15PCH": "Physical Chemistry III",
    "6B16PCH": "Physical Methods in Chemistry",
    "6B17PCH": "Environmental Chemistry",
    "6B11PCH": "Practicals 3: Gravimetric Analysis ",
    "6B12PCH": "Practicals 4: Organic Chemistry",
    "6B13PCH": "Project & Industrial Visit",
    "4C04BOT": "Plant Physiology, Ecology and Applied Botany",
    "2B02ICSC": "Advanced C Programming",
}

